server:
  port: 3344
spring:
  application:
    name: springcloud-study-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gongxings/springcloud-study-config.git
          search-paths: config-repo
          username:  lapulasi2019
          password:  zhang26189152008